### ISSUE TITLE
[android] Can't build app-tester

### ISSUE THREAD

**Issue by shawninder** [vigour-io/wrapper#199]
Using the latest version of wrapper#master, I can't build app-tester for android, getting this error:

```
:app:processDebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Error: more than one library with package name 'io.vigour.plugin.statusbar'
  You can temporarily disable this error with android.enforceUniquePackageName=false
  However, this is temporary and will be enforced in 1.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 18.331 secs
ERR! android Error: failed command
ERR! android     at ChildProcess.<anonymous> (/Users/shawn/Work/wrapper/lib/exe.js:41:21)
ERR! android     at emitTwo (events.js:87:13)
ERR! android     at ChildProcess.emit (events.js:172:7)
ERR! android     at maybeClose (internal/child_process.js:818:16)
ERR! android     at Socket.<anonymous> (internal/child_process.js:319:11)
ERR! android     at emitOne (events.js:77:13)
ERR! android     at Socket.emit (events.js:169:7)
ERR! android     at Pipe._onclose (net.js:469:12)
ERR! android  { [Error: failed command]
ERR! android   info:
ERR! android    { code: 1,
ERR! android      command: './gradlew assembleDebug -PverCode=2 -PverName=2.0.0 -PandroidAppId=io.vigour.tester -PRELEASE_STORE_PASSWORD=********** -PRELEASE_KEY_ALIAS=blabla -PRELEASE_KEY_PASSWORD=**********' } } {"stack":"Error: failed command\n    at ChildProcess.<anonymous> (/Users/shawn/Work/wrapper/lib/exe.js:41:21)\n    at emitTwo (events.js:87:13)\n    at ChildProcess.emit (events.js:172:7)\n    at maybeClose (internal/child_process.js:818:16)\n    at Socket.<anonymous> (internal/child_process.js:319:11)\n    at emitOne (events.js:77:13)\n    at Socket.emit (events.js:169:7)\n    at Pipe._onclose (net.js:469:12)","message":"failed command","info":{"code":1,"command":"./gradlew assembleDebug -PverCode=2 -PverName=2.0.0 -PandroidAppId=io.vigour.tester -PRELEASE_STORE_PASSWORD=********** -PRELEASE_KEY_ALIAS=blabla -PRELEASE_KEY_PASSWORD=**********"}} Error: failed command
ERR! android     at ChildProcess.<anonymous> (/Users/shawn/Work/wrapper/lib/exe.js:41:21)
ERR! android     at emitTwo (events.js:87:13)
ERR! android     at ChildProcess.emit (events.js:172:7)
ERR! android     at maybeClose (internal/child_process.js:818:16)
ERR! android     at Socket.<anonymous> (internal/child_process.js:319:11)
ERR! android     at emitOne (events.js:77:13)
ERR! android     at Socket.emit (events.js:169:7)
ERR! android     at Pipe._onclose (net.js:469:12)
```

Repro steps:

clone app-tester and go in that directory, then
- `npm i`
- `npm run android`

@marcusbesjes Can you assign this to either @michielibiza or @tvervest ?

**Comment by tvervest** [comment]
I'll have a quick look

**Comment by shawninder** [comment]
hmm pushed some fixes to wrapper but I didn't publish... You may want to link it. Or publish it.... @tvervest

**Comment by tvervest** [comment]
@shawninder could you verify the fix?

**Comment by shawninder** [comment]
Doesn't work, back to you :)
